# Generated by Django 6.1.1 on 2026-09-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_geoprofs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.IntegerField()),
                ('used_balance', models.IntegerField()),
            ],
        ),
    ]
